version: '3.9'

services:
  app:
    build: .
    ports:
      - "5005:5005"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app   # For development (hot reload)
      - /app/node_modules   # Prevent overwriting container modules
    command: npm run dev           # Use ts-node for development

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: swift-deliver
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: